### ISSUE TITLE
Incorrect cast in Uart::begin

### ISSUE THREAD

**Issue by keestux** [arduino/ArduinoCore-samd#216]
See issue #83 where I left this note. I might as well create a new issue.
Issue #83 is not fixed properly. Argument config was changed to uint16_t as shown below

    void Uart::begin(unsigned long baudrate, uint16_t config)

however the other Uart::begin calls it with a cast to uint8_t

    void Uart::begin(unsigned long baudrate)
    {
      begin(baudrate, (uint8_t)SERIAL_8N1);
    }

So far, nobody noticed, probably because nobody uses other than 8 data bits. In that case you won't notice the bug.
Wouldn't it be better to drop this latter function and to add a default value for config in the other begin()?

**Comment by cmaglie** [comment]
Indeed `SERIAL_8N1` is `0x0413`, so with the cast to uint8 we lose the `0x04..` that is the ["8 data bits"](https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/HardwareSerial.h#L26) part:

```c++
#define HARDSER_DATA_5	 	(0x100ul)
#define HARDSER_DATA_6	 	(0x200ul)
#define HARDSER_DATA_7	 	(0x300ul)
#define HARDSER_DATA_8	 	(0x400ul)
#define HARDSER_DATA_MASK	(0xF00ul)
```

BTW this doesn't trigger the bug since the [`extractCharSize`](https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/Uart.cpp#L114) defaults to 8 bits anyway:

```c++
  switch(config & HARDSER_DATA_MASK)
  {
    case HARDSER_DATA_5:
      return UART_CHAR_SIZE_5_BITS;

    case HARDSER_DATA_6:
      return UART_CHAR_SIZE_6_BITS;

    case HARDSER_DATA_7:
      return UART_CHAR_SIZE_7_BITS;

    case HARDSER_DATA_8:
    default:
      return UART_CHAR_SIZE_8_BITS;
  }
```

this explains why nobody noticed it until now.

Thanks for the bug report!
