### ISSUE TITLE
MKR NB 1500 Unsupported in when compiling UpdateBootloader

### ISSUE THREAD

**Issue by bleckers** [arduino/ArduinoCore-samd#434]
While trying to compile the UpdateBootloader code for the MKR 1500 (from File>Examples>Examples for Arduino MKR NB 1500>SAMD_BootloaderUpdater>UpdateBootloader), I get the following error:

```
C:\Users\[user]\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.3\libraries\SAMD_BootloaderUpdater\src\SAMD_BootloaderUpdater.cpp:32:4: error: #error "Unsupported board!"

   #error "Unsupported board!"

    ^~~~~

Using library SAMD_BootloaderUpdater at version 1.0 in folder: C:\Users\[user]\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.3\libraries\SAMD_BootloaderUpdater 
exit status 1
Error compiling for board Arduino MKR NB 1500.
```
Is there any way to update the bootloader on this device apart from using the Atmel-ICE?

**Comment by facchinm** [comment]
Hi @bleckers ,
the bootloader update was just meant for the MKRVidor since there was a bug preventing the FPGA image to be uploaded. 
You can use the same approach, though, to update any board with the right bootloader (the procedure on how to convert a bin file to the right format is here https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/SAMD_BootloaderUpdater/extras/build.sh)
Please note that the procedure is not risk-free, so having a programmer (Atmel ICE or any CMSIS-DAP compatible) at hand might be a good idea :wink:
