### ISSUE TITLE
failure in high speed communication

### ISSUE THREAD

**Issue by ROBOTIS-Will** [arduino/ArduinoCore-samd#542]
Hi,

This issue is an explanation of test result regarding the PR #541.
While we've been testing with Arduino MKR boards, there was an issue with unsuccessful transmission caused by the flushUART(). 

In our test we were using half duplex communication(TTL) over the UART to control TX and RX direction with the direction control GPIO pin. After flushing the UART, direction control will be switched, but the flushUART does not wait until the completion of TX.

Please see below oscilloscope graph where the direction control(in blue) drops too early before the end of TX(in green), therefore, the actual TX data is missing the last bit(in yellow).

![Torque On 2Mbps #1](https://user-images.githubusercontent.com/26239359/86987164-59aba180-c1d0-11ea-92bd-dd1e105beafe.png)

After commenting out the isDataRegisterEmptyUART() section, flushUART() waits until the end of transmission as below.
![Torque On 2Mbps #2(check TXC only)](https://user-images.githubusercontent.com/26239359/86987300-b0b17680-c1d0-11ea-9240-0c1462b6fe21.png)

As we are not sure the reason of skipping the checking transmission completion, please review this modification(#541) and let us know.
Thank you.

**Comment by matedl** [comment]
I have the same problem when writing a single byte over half duplex RS-485. When I write multiple bytes, flush() works as it should but when I write a single byte it does not work. When writing a single byte "isDataRegisterEmptyUART()" probably returns true since the byte is already in the shift register and flush() returns without waiting for TXC. Maybe this problem was introduced when fixing the issue "Fix Serial.flush() blocking if called immediately after Serial.begin() #144"?

**Comment by ROBOTIS-Will** [comment]
@facchinm Hi, I'm just checking in for any updates or progress on this issue. Hope you are safe from the Covid-19.

**Comment by facchinm** [comment]
Patch #541 merged, will be part of core 1.8.11 :slightly_smiling_face:
