### ISSUE TITLE
regression: OTA updates no longer working on Wifi1010 & SAMD M0 release 1.8.8

### ISSUE THREAD

**Issue by Tdegussem** [arduino/ArduinoCore-samd#563]
When trying to do an Over-the-Air update on a maker board (Wifi1010), the board hangs after OTA flashing:

ArduinoOTA example,  do ethernet port upload using OTA 1.8.8:
- IDE shows successfull flashing 'OK - Sketch uploaded successfully' --> Auto-Reset --> Board is unresponsive (No COM port, no USB hotplugging)
ArduinoOTA example,  do ethernet port upload using OTA 1.8.7:
- IDE shows successful flashing 'OK - Sketch uploaded successfully' --> Auto-Reset --> Board is functional

I can reproduce this by up- or downgrading the board definition version.

**Comment by jandrassy** [comment]
additional information. the cause is 
`mkrwifi1010.arduinoota.extraflags=-d`
in boards.txt

this is for the 'new' OTA. does it work? is it documented?

**Comment by facchinm** [comment]
Hi @jandrassy ,
the `-d` flag was meant to allow offloading the download to Nina module (https://github.com/arduino/arduinoOTA/blob/master/main.go#L39) .
The problem is that, for security reasons, the second stage bootloader now requires an image with a particular header, so passing the raw binary will not work.
@aentinger should we revert the `-d` or adapt `arduinoota` to create and serve the correct binary?

**Comment by jandrassy** [comment]
@facchinm Martino, right now here the problem is a conflict with the WIFi101OTA library. Until the new OTA download is ready and documented there shouldn't be the `mkrwifi1010.arduinoota.extraflags=-d` line in boards.txt.

It looks like the file is downloaded by firmware from arduinoOTA server at the same time as it is uploaded by arduinoOTA to WiFi101OTA server. But I don't know yet why it is a problem.

**Comment by aentinger** [comment]
Hi :wave: I've got next to no idea (really no idea actually) how OTA via IDE works. However, [here](https://github.com/arduino-libraries/ArduinoIoTCloud/tree/master/extras/tools) are the tools to prefix the binary with the required data. I should note however that those requires using [ArduinoCore-samd:master:HEAD](https://github.com/arduino/ArduinoCore-samd/tree/9f92beeecd6d29381be3cb398432aafabf198ded) since there's been no release since the latest changes to **SNU**. What's the fastest strategy to get to a fix here?

**Comment by jandrassy** [comment]
that was fast :-). thank you

**Comment by aentinger** [comment]
Yeah @jandrassy ... a release was already in the air :cloud_with_lightning: :wink:
