### ISSUE TITLE
Unable to set the number of data bits on serial port in Uart::begin due to data type width

### ISSUE THREAD

**Issue by TomKeddie** [arduino/ArduinoCore-samd#83]
These constants for the number of data bits are all 16 bit values.
```
#define HARDSER_DATA_5	 	(0x100ul)
#define HARDSER_DATA_6	 	(0x200ul)
#define HARDSER_DATA_7	 	(0x300ul)
#define HARDSER_DATA_8	 	(0x400ul)
#define HARDSER_DATA_MASK	(0xF00ul)`
```
But Uart::begin takes an 8 bit value
`    void begin(unsigned long baudrate, uint8_t config);`

This makes it impossible to change the number of bits.

**Comment by keestux** [comment]
This problem is not fixed properly. Argument config was changed to uint16_t as shown below

    void Uart::begin(unsigned long baudrate, uint16_t config)

however the other Uart::begin calls it with a cast to uint8_t

    void Uart::begin(unsigned long baudrate)
    {
      begin(baudrate, (uint8_t)SERIAL_8N1);
    }

So far, nobody noticed, probably because nobody uses other than 8 data bits. In that case you won't notice the bug.
Wouldn't it be better to drop this latter function and to add a default value for config in the other begin()?
